language: python
python: '3.8'
sudo: required
services:
- docker
notifications:
  email:
    recipients:
    - tgu@anl.gov
    on_success: never
    on_failure: always
branches:
  only:
  - master
before_install:
- docker version
- python --version
- javac -version
- java -version
install:
- pip install coveralls
- docker pull kbase/kb-sdk
- mkdir $HOME/bin/
- docker run kbase/kb-sdk genscript > $HOME/bin/kb-sdk
- chmod +x $HOME/bin/kb-sdk
- export PATH=$PATH:$HOME/bin/
- echo "export PATH=\$PATH:$HOME/bin/" >> ~/.bashrc
- kb-sdk version
script:
- kb-sdk validate
